// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Generated events.
#include PLATFORM_HEADER
#include "stack/include/ember-types.h"
#include "hal/hal.h"


void stateEventHandler(void);
extern EmberEventControl stateEventControl;

void i2cEventHandler(void);
extern EmberEventControl i2cEventControl;

void userEventHandler(void);
extern EmberEventControl userEventData;



const EmberEventData emAppEvents[] = {
  {&stateEventControl, stateEventHandler},
  {&i2cEventControl, i2cEventHandler},
  {&userEventData, userEventHandler},
  {NULL, NULL}
};
